In [2]:
# ニューラルネットワーククラスの定義
# ３つの関数はこのクラスに属する


class neuralNetwork:
    
    # ニューラルネットワークの初期化
    def __init__(self, inputnodes, hiddennodes, outputnodes, learningrate):
        # 入力層・隠れ層・出力層のノード数の設定
        self.inodes = inputnodes # 入力層
        self.hnodes = hiddennodes # 隠れ層
        self.onodes = outputnodes # 出力層
        
        # リンクの重み行列 wih,who
        # 行列内の重み wij = ノードjから次の層のノードjへのリンクの重み
        
        # 行列
        # W11 W21
        # W12 W22
        # などを作成する
        
        # 入力層→隠れ層へのリンクの重み（wih）
        self.wih = numpy.random.normal(0.0, pow(self.inodes, -0.5), (self.hnodes, self.inodes))
        # 隠れ層→出力層へのリンクの重み（who）
        self.who = numpy.random.normal(0.0, pow(self.hnodes, -0.5), (self.onodes, self.hnodes))
        
        # 活性化関数はシグモイド関数
        self.activation_function = lambda x: scipy.special.expit(x)
        
        # 学習率の設定
        self.lr = learningrate
        
        pass # 関数の終わり
    
    # ニューラルネットワークの学習
    def train():
        pass
    
    # ニューラルネットワークの答えの出力
    def query():
        pass
    

# ---ユーザ設定---
# 入力層・隠れ層・出力層のノード数の設定
input_nodes = 3
hidden_nodes = 3
output_nodes =3

# 学習率の設定
learning_rate = 0.3

#ニューラルネットワークのインスタンスの生成
n = neuralNetwork(input_nodes, hidden_nodes, output_nodes, learning_rate)



NameError: name 'numpy' is not defined

In [3]:
# ニューラルネットワーククラスの定義
# ３つの関数はこのクラスに属する


class neuralNetwork:
    
    # ニューラルネットワークの初期化
    def __init__(self, inputnodes, hiddennodes, outputnodes, learningrate):
        # 入力層・隠れ層・出力層のノード数の設定
        self.inodes = inputnodes # 入力層
        self.hnodes = hiddennodes # 隠れ層
        self.onodes = outputnodes # 出力層
        
        # リンクの重み行列 wih,who
        # 行列内の重み wij = ノードjから次の層のノードjへのリンクの重み
        
        # 行列
        # W11 W21
        # W12 W22
        # などを作成する
        
        # 入力層→隠れ層へのリンクの重み（wih）
        self.wih = numpy.random.normal(0.0, pow(self.inodes, -0.5), (self.hnodes, self.inodes))
        # 隠れ層→出力層へのリンクの重み（who）
        self.who = numpy.random.normal(0.0, pow(self.hnodes, -0.5), (self.onodes, self.hnodes))
        
        # 活性化関数はシグモイド関数
        self.activation_function = lambda x: scipy.special.expit(x)
        
        # 学習率の設定
        self.lr = learningrate
        
        pass # 関数の終わり
    
    # ニューラルネットワークの学習
    def train():
        pass
    
    # ニューラルネットワークの答えの出力
    def query():
        pass
    

# ---ユーザ設定---
# 入力層・隠れ層・出力層のノード数の設定
input_nodes = 3
hidden_nodes = 3
output_nodes =3

# 学習率の設定
learning_rate = 0.3

#ニューラルネットワークのインスタンスの生成
n = neuralNetwork(input_nodes, hidden_nodes, output_nodes, learning_rate)



NameError: name 'numpy' is not defined

In [4]:
import numpy

# ニューラルネットワーククラスの定義
# ３つの関数はこのクラスに属する


class neuralNetwork:
    
    # ニューラルネットワークの初期化
    def __init__(self, inputnodes, hiddennodes, outputnodes, learningrate):
        # 入力層・隠れ層・出力層のノード数の設定
        self.inodes = inputnodes # 入力層
        self.hnodes = hiddennodes # 隠れ層
        self.onodes = outputnodes # 出力層
        
        # リンクの重み行列 wih,who
        # 行列内の重み wij = ノードjから次の層のノードjへのリンクの重み
        
        # 行列
        # W11 W21
        # W12 W22
        # などを作成する
        
        # 入力層→隠れ層へのリンクの重み（wih）
        self.wih = numpy.random.normal(0.0, pow(self.inodes, -0.5), (self.hnodes, self.inodes))
        # 隠れ層→出力層へのリンクの重み（who）
        self.who = numpy.random.normal(0.0, pow(self.hnodes, -0.5), (self.onodes, self.hnodes))
        
        # 活性化関数はシグモイド関数
        self.activation_function = lambda x: scipy.special.expit(x)
        
        # 学習率の設定
        self.lr = learningrate
        
        pass # 関数の終わり
    
    # ニューラルネットワークの学習
    def train():
        pass
    
    # ニューラルネットワークの答えの出力
    def query():
        pass
    

# ---ユーザ設定---
# 入力層・隠れ層・出力層のノード数の設定
input_nodes = 3
hidden_nodes = 3
output_nodes =3

# 学習率の設定
learning_rate = 0.3

#ニューラルネットワークのインスタンスの生成
n = neuralNetwork(input_nodes, hidden_nodes, output_nodes, learning_rate)



In [5]:
import numpy

# ニューラルネットワーククラスの定義
# ３つの関数はこのクラスに属する


class neuralNetwork:
    
    # ニューラルネットワークの初期化
    def __init__(self, inputnodes, hiddennodes, outputnodes, learningrate):
        # 入力層・隠れ層・出力層のノード数の設定
        self.inodes = inputnodes # 入力層
        self.hnodes = hiddennodes # 隠れ層
        self.onodes = outputnodes # 出力層
        
        # リンクの重み行列 wih,who
        # 行列内の重み wij = ノードjから次の層のノードjへのリンクの重み
        
        # 行列
        # W11 W21
        # W12 W22
        # などを作成する
        
        # 入力層→隠れ層へのリンクの重み（wih）
        self.wih = numpy.random.normal(0.0, pow(self.inodes, -0.5), (self.hnodes, self.inodes))
        # 隠れ層→出力層へのリンクの重み（who）
        self.who = numpy.random.normal(0.0, pow(self.hnodes, -0.5), (self.onodes, self.hnodes))
        
        # 活性化関数はシグモイド関数
        self.activation_function = lambda x: scipy.special.expit(x)
        
        # 学習率の設定
        self.lr = learningrate
        
        pass # 関数の終わり
    
    # ニューラルネットワークの学習
    def train():
        pass
    
    # ニューラルネットワークの答えの出力
    def query():
        pass
    

# ---ユーザ設定---
# 入力層・隠れ層・出力層のノード数の設定
input_nodes = 3
hidden_nodes = 3
output_nodes =3

# 学習率の設定
learning_rate = 0.3

#ニューラルネットワークのインスタンスの生成
n = neuralNetwork(input_nodes, hidden_nodes, output_nodes, learning_rate)




In [6]:
# ライブラリのインポート
import numpy
import scipy.special

# ニューラルネットワーククラスの定義
# ３つの関数はこのクラスに属する
class neuralNetwork:
    
    # ニューラルネットワークの初期化
    def __init__(self, inputnodes, hiddennodes, outputnodes, learningrate):
        # 入力層・隠れ層・出力層のノード数の設定
        self.inodes = inputnodes # 入力層
        self.hnodes = hiddennodes # 隠れ層
        self.onodes = outputnodes # 出力層
        
        # リンクの重み行列 wih,who
        # 行列内の重み wij = ノードjから次の層のノードjへのリンクの重み
        
        # 行列
        # W11 W21
        # W12 W22
        # などを作成する
        
        # 入力層→隠れ層へのリンクの重み（wih）
        self.wih = numpy.random.normal(0.0, pow(self.inodes, -0.5), (self.hnodes, self.inodes))
        # 隠れ層→出力層へのリンクの重み（who）
        self.who = numpy.random.normal(0.0, pow(self.hnodes, -0.5), (self.onodes, self.hnodes))
        
        # 学習率の設定
        self.lr = learningrate
        
        # 活性化関数はシグモイド関数
        self.activation_function = lambda x: scipy.special.expit(x)
        
        pass # 関数の終わり
    
    # ニューラルネットワークの学習
    def train():
        pass
    
    # ニューラルネットワークの答えの出力
    def query():
        pass
    

# ---ユーザ設定---
# 入力層・隠れ層・出力層のノード数の設定
input_nodes = 3
hidden_nodes = 3
output_nodes =3

# 学習率の設定
learning_rate = 0.3

#ニューラルネットワークのインスタンスの生成
n = neuralNetwork(input_nodes, hidden_nodes, output_nodes, learning_rate)



In [1]:
# ライブラリのインポート
import numpy
import scipy.special

# ニューラルネットワーククラスの定義
# ３つの関数はこのクラスに属する
class neuralNetwork:
    
    # ニューラルネットワークの初期化
    def __init__(self, inputnodes, hiddennodes, outputnodes, learningrate):
        # 入力層・隠れ層・出力層のノード数の設定
        self.inodes = inputnodes # 入力層
        self.hnodes = hiddennodes # 隠れ層
        self.onodes = outputnodes # 出力層
        
        # リンクの重み行列 wih,who
        # 行列内の重み wij = ノードjから次の層のノードjへのリンクの重み
        
        # 行列
        # W11 W21
        # W12 W22
        # などを作成する
        
        # 入力層→隠れ層へのリンクの重み（wih）
        self.wih = numpy.random.normal(0.0, pow(self.inodes, -0.5), (self.hnodes, self.inodes))
        # 隠れ層→出力層へのリンクの重み（who）
        self.who = numpy.random.normal(0.0, pow(self.hnodes, -0.5), (self.onodes, self.hnodes))
        
        # 学習率の設定
        self.lr = learningrate
        
        # 活性化関数はシグモイド関数
        self.activation_function = lambda x: scipy.special.expit(x)
        
        pass # 関数の終わり
    
    # ニューラルネットワークの学習
    def train():
        pass
    
    # ニューラルネットワークの答えの出力
    def query(self, inputs_list):
        # 入力リストを行列に変換（.Tを使って転置している）
        inputs = numpy.array(inputs_list, ndmin=2).T
        
        # 入力信号が隠れ層に入ってくるまでの計算
        hidden_inputs = numpy.dot(self.wih, inputs)
        # 隠れ層からの信号にシグモイド関数を作用させて出力層へ渡す
        hidden_outputs = self.activation_function(hidden_inputs)
 
        # 出力層に入ってくる信号の計算
        final_inputs = numpy.dot(self.who, hidden_outputs)
        # 出力層からの信号にシグモイド関数を作用させて最終的な出力とする
        final_outputs = self.activation_function(final_inputs)
 
        # 関数の戻り値として最終的な出力結果を返す
        return final_outputs
    

# ---ユーザ設定---
# 入力層・隠れ層・出力層のノード数の設定
input_nodes = 3
hidden_nodes = 3
output_nodes =3

# 学習率の設定
learning_rate = 0.3

#ニューラルネットワークのインスタンスの生成
n = neuralNetwork(input_nodes, hidden_nodes, output_nodes, learning_rate)

# query(　)関数の呼び出し（テスト用）
print(n.query([1.0, 0.5, -0.5]))

[[0.45017551]
 [0.66024559]
 [0.56344062]]


In [1]:
# ライブラリのインポート
import numpy
import scipy.special

# ニューラルネットワーククラスの定義
# ３つの関数はこのクラスに属する
class neuralNetwork:
    
    # ニューラルネットワークの初期化
    def __init__(self, inputnodes, hiddennodes, outputnodes, learningrate):
        # 入力層・隠れ層・出力層のノード数の設定
        self.inodes = inputnodes # 入力層
        self.hnodes = hiddennodes # 隠れ層
        self.onodes = outputnodes # 出力層
        
        # リンクの重み行列 wih,who
        # 行列内の重み wij = ノードjから次の層のノードjへのリンクの重み
        
        # 行列
        # W11 W21
        # W12 W22
        # などを作成する
        
        # 入力層→隠れ層へのリンクの重み（wih）
        self.wih = numpy.random.normal(0.0, pow(self.inodes, -0.5), (self.hnodes, self.inodes))
        # 隠れ層→出力層へのリンクの重み（who）
        self.who = numpy.random.normal(0.0, pow(self.hnodes, -0.5), (self.onodes, self.hnodes))
        
        # 学習率の設定
        self.lr = learningrate
        
        # 活性化関数はシグモイド関数
        self.activation_function = lambda x: scipy.special.expit(x)
        
        pass # 関数の終わり
    
    # ニューラルネットワークの学習
    def train():
        pass
    
    # ニューラルネットワークの答えの出力
    def query(self, inputs_list):
        # 入力リストを行列に変換（.Tを使って転置している）
        inputs = numpy.array(inputs_list, ndmin=2).T
        
        # 入力信号が隠れ層に入ってくるまでの計算
        hidden_inputs = numpy.dot(self.wih, inputs)
        # 隠れ層からの信号にシグモイド関数を作用させて出力層へ渡す
        hidden_outputs = self.activation_function(hidden_inputs)
 
        # 出力層に入ってくる信号の計算
        final_inputs = numpy.dot(self.who, hidden_outputs)
        # 出力層からの信号にシグモイド関数を作用させて最終的な出力とする
        final_outputs = self.activation_function(final_inputs)
 
        # 関数の戻り値として最終的な出力結果を返す
        return final_outputs
    

# ---ユーザ設定---
# 入力層・隠れ層・出力層のノード数の設定
input_nodes = 3
hidden_nodes = 3
output_nodes =3

# 学習率の設定
learning_rate = 0.3

#ニューラルネットワークのインスタンスの生成
n = neuralNetwork(input_nodes, hidden_nodes, output_nodes, learning_rate)

# query(　)関数の呼び出し（テスト用）
print(n.query([1.0, 0.5, -0.5]))

[[0.59708885]
 [0.47080833]
 [0.39080872]]


In [2]:
# ライブラリのインポート
import numpy
import scipy.special

# ニューラルネットワーククラスの定義
# ３つの関数はこのクラスに属する
class neuralNetwork:
    
    # ニューラルネットワークの初期化
    def __init__(self, inputnodes, hiddennodes, outputnodes, learningrate):
        # 入力層・隠れ層・出力層のノード数の設定
        self.inodes = inputnodes # 入力層
        self.hnodes = hiddennodes # 隠れ層
        self.onodes = outputnodes # 出力層
        
        # リンクの重み行列 wih,who
        # 行列内の重み wij = ノードjから次の層のノードjへのリンクの重み
        
        # 行列
        # W11 W21
        # W12 W22
        # などを作成する
        
        # 入力層→隠れ層へのリンクの重み（wih）
        self.wih = numpy.random.normal(0.0, pow(self.inodes, -0.5), (self.hnodes, self.inodes))
        # 隠れ層→出力層へのリンクの重み（who）
        self.who = numpy.random.normal(0.0, pow(self.hnodes, -0.5), (self.onodes, self.hnodes))
        
        # 学習率の設定
        self.lr = learningrate
        
        # 活性化関数はシグモイド関数
        self.activation_function = lambda x: scipy.special.expit(x)
        
        pass # 関数の終わり
    
    # ニューラルネットワークの学習
    def train(self, inputs_list, targets_list):
        # 入力リストを行列に変換
        inputs = numpy.array(inputs_list, ndmin=2).T
        # 真偽リストを行列に変換
        targets = numpy.array(targets_list, ndmin=2).T
        
        # 隠れ層に入ってくる信号の計算
        hidden_inputs = numpy.dot(self.wih, inputs)
        # 隠れ層から出る信号に活性化関数を作用させる
        hidden_outputs = self.activation_function(hidden_inputs)
        
        # 出力層に入ってくる信号の計算
        final_inputs = numpy.dot(self.who, hidden_outputs)
        # 出力層から出る最終的な出力に活性化関数を作用させる
        final_outputs = self.activation_function(final_inputs)
        
        # 出力の誤差　＝　真偽　ー　最終的な出力
        output_errors = targets - final_outputs
        # 隠れ層に伝播された誤差はリンクの重みづけをして結合
        hidden_errors = numpy.dot(self.who.T, output_errors)
        
        # 隠れ層と出力層間のリンクの重みの更新
        self.who += self.lr * numpy.dot( \
            (output_errors * final_outputs * (1.0 - final_outputs)), \
            numpy.transpose(hidden_outputs))
        
        # 入力層と隠れ層間のリンクの重みの更新
        self.wih += self.lr * numpy.dot( \
           (hidden_errors * hidden_outputs * (1.0 - hidden_outputs)), \
            numpy.transpose(inputs))
        
        pass 
    
    # ニューラルネットワークの答えの出力
    def query(self, inputs_list):
        # 入力リストを行列に変換（.Tを使って転置している）
        inputs = numpy.array(inputs_list, ndmin=2).T
        
        # 入力信号が隠れ層に入ってくるまでの計算
        hidden_inputs = numpy.dot(self.wih, inputs)
        # 隠れ層からの信号にシグモイド関数を作用させて出力層へ渡す
        hidden_outputs = self.activation_function(hidden_inputs)
 
        # 出力層に入ってくる信号の計算
        final_inputs = numpy.dot(self.who, hidden_outputs)
        # 出力層からの信号にシグモイド関数を作用させて最終的な出力とする
        final_outputs = self.activation_function(final_inputs)
 
        # 関数の戻り値として最終的な出力結果を返す
        return final_outputs
    

# ---ユーザ設定---
# 入力層・隠れ層・出力層のノード数の設定
input_nodes = 3
hidden_nodes = 3
output_nodes =3

# 学習率の設定
learning_rate = 0.3

#ニューラルネットワークのインスタンスの生成
n = neuralNetwork(input_nodes, hidden_nodes, output_nodes, learning_rate)

# query(　)関数の呼び出し（テスト用）
print(n.query([1.0, 0.5, -0.5]))

[[0.35019612]
 [0.41978682]
 [0.41256303]]
